# VLMP-8X-000001 - VMware Aria Suite Lifecycle vpostgres must limit the number of concurrent sessions.
- name: VLMP-8X-000001 - VMware Aria Suite Lifecycle vpostgres must limit the number of concurrent sessions
  tags: [VLMP-8X-000001]
  block:
    - name: VLMP-8X-000001 - Check number of concurrent sessions configured
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW max_connections"
      register: max_conn_out
      changed_when: false

    - name: VLMP-8X-000001 - Set number of concurrent sessions(max_connections)
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -c "ALTER SYSTEM SET max_connections = {{ postgres_max_connections }};"
      when: max_conn_out.stdout == "" or max_conn_out.stdout | int < 1
      register: upd_max_conn
      changed_when: upd_max_conn.rc == 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000006 - VMware Aria Suite Lifecycle vpostgres configuration files must not be accessible by unauthorized users.
- name: VLMP-8X-000006 - VMware Aria Suite Lifecycle vpostgres configuration files must not be accessible by unauthorized users
  tags: [VLMP-8X-000006]
  block:
    - name: VLMP-8X-000006 - Search for files with permissions other than 600 and owner not as postgres
      ansible.builtin.shell: find {{ postgres_data_dir }}/*conf* -xdev -type f -a '(' -not -perm 600 -o -not -user {{ postgres_owner }} -o -not -group {{ postgres__group }} ')' -exec ls -d {} \;
      register: file_search_out
      changed_when: false

    - name: VLMP-8X-000006 - Updating file permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: file
        owner: '{{ postgres_owner }}'
        group: '{{ postgres__group }}'
        mode: '600'
      when: file_search_out.stdout != ""
      with_items:
        - "{{ file_search_out.stdout_lines }}"

###################################################################################################################################

# VLMP-8X-000010 - VMware Aria Suite Lifecycle vpostgres must produce logs containing sufficient information to establish what type of events occurred.
- name: VLMP-8X-000010 - VMware Aria Suite Lifecycle vpostgres must produce logs containing sufficient information to establish what type of events occurred
  tags: [VLMP-8X-000010]
  block:
    - name: VLMP-8X-000010 - Show log line prefix
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_line_prefix"
      register: log_pref_out
      changed_when: false

    - name: VLMP-8X-000010 - Updating log pattern
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -c "ALTER SYSTEM SET log_line_prefix = '%m %c %x %d %u %r %p %l';"
      when: log_pref_out.stdout != "%m %c %x %d %u %r %p %l"
      register: upd_log_pref
      changed_when: upd_log_pref.rc == 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000020 - VMware Aria Suite Lifecycle vpostgres must be configured to protect log files from unauthorized access.
- name: VLMP-8X-000020 - VMware Aria Suite Lifecycle vpostgres must be configured to protect log files from unauthorized access
  tags: [VLMP-8X-000020]
  block:
    - name: VLMP-8X-000020 - Show log file mode
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_file_mode;"
      register: log_file_out
      changed_when: false

    - name: VLMP-8X-000020 - Updating log file mode
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET log_file_mode = '0600';"
      when: log_file_out.stdout != "0600"
      register: upd_file_mode
      changed_when: upd_file_mode.rc == 0
      notify:
        - Restart Postgres

    - name: VLMP-8X-000020 - Find out log directory
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_directory;"
      register: log_dir_out
      changed_when: false

    - name: VLMP-8X-000020 - Find out data directory
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW data_directory;"
      register: data_dir_out
      changed_when: false

    - name: VLMP-8X-000020 - Generate complete path for log destination
      ansible.builtin.set_fact:
        log_dest: "{{ data_dir_out.stdout }}/{{ log_dir_out.stdout }}"
      when: '"/" not in log_dir_out.stdout'
      changed_when: false

    - name: VLMP-8X-000020 - Generate complete path for log destination
      ansible.builtin.set_fact:
        log_dest: "{{ log_dir_out.stdout }}"
      when: '"/" in log_dir_out.stdout'
      changed_when: false

    - name: VLMP-8X-000020 - Find files under log destination directory with incorrect permissions
      ansible.builtin.shell: find {{ log_dest }}/* -xdev -type f -a '(' -not -perm 600 -o -not -user postgres -o -not -group users ')' -exec ls {} \;
      register: find_files_out
      changed_when: false
      failed_when: false

    - name: VLMP-8X-000020 - Updating file ownership and permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: file
        owner: 'postgres'
        group: 'users'
        mode: '600'
      when: find_files_out.stdout != ""
      with_items:
        - "{{ find_files_out.stdout_lines }}"

###################################################################################################################################

# VLMP-8X-000032 - VMware Aria Suite Lifecycle vpostgres must not load unused database components, software, and database objects.
- name: VLMP-8X-000032 - VMware Aria Suite Lifecycle vpostgres must not load unused database components, software, and database objects
  tags: [VLMP-8X-000032]
  block:
    - name: VLMP-8X-000032 - List pgextensions
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "select extname from pg_extension where extname != 'plpgsql';"
      register: ext_out
      changed_when: false

    - name: VLMP-8X-000032 - Remove extensions other than plpgsql
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "DROP EXTENSION {{ item | trim }};"
      when: ext_out.stdout != "" and item | trim not in postgres_approved_extensions
      register: upd_ext
      changed_when: upd_ext.rc == 0
      with_items:
        - "{{ ext_out.stdout_lines }}"

###################################################################################################################################

# VLMP-8X-000035 - VMware Aria Suite Lifecycle vpostgres must be configured to use an authorized port.
- name: VLMP-8X-000035 - VMware Aria Suite Lifecycle vpostgres must be configured to use an authorized port
  tags: [VLMP-8X-000035]
  block:
    - name: VLMP-8X-000035 - Check for the port postgres is using
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW port;"
      register: port_out
      changed_when: false

    - name: VLMP-8X-000035 - Set postgres port
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET port TO '5432';"
      when: port_out.stdout != "5432"
      register: upd_port
      changed_when: upd_port.rc != 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000051 - VMware Aria Suite Lifecycle vpostgres must write log entries to disk prior to returning operation success or failure.
- name: VLMP-8X-000051 - VMware Aria Suite Lifecycle vpostgres must write log entries to disk prior to returning operation success or failure
  tags: [VLMP-8X-000051]
  block:
    - name: VLMP-8X-000051 - Check for the postgres settings
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SELECT name, setting FROM pg_settings WHERE name IN ('fsync','full_page_writes','synchronous_commit');"
      register: pg_settings_out
      changed_when: false

    - name: VLMP-8X-000051 - Update settings to turn on
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET {{ item.split('|')[0] }} TO 'on';"
      when:
        - pg_settings_out.stdout != ""
        - item.split('|')[1] | trim != "on"
      with_items:
        - "{{ pg_settings_out.stdout_lines }}"
      register: set_pg_settings
      changed_when: set_pg_settings.rc == 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000060 - VMware Aria Suite Lifecycle vpostgres must provide non-privileged users with minimal error information.
- name: VLMP-8X-000060 - VMware Aria Suite Lifecycle vpostgres must provide non-privileged users with minimal error information
  tags: [VLMP-8X-000060]
  block:
    - name: VLMP-8X-00060 - Verify client_min_messages configuration
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW client_min_messages;"
      register: client_min_msg
      changed_when: false

    - name: VLMP-8X-000060 - Set client_min_messages to error
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET client_min_messages TO 'error';"
      when: client_min_msg.stdout != "error"
      register: set_client_min_msg
      changed_when: set_client_min_msg.rc == 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000070 - VMware Aria Suite Lifecycle vpostgres must have log collection enabled.
- name: VLMP-8X-000070 - VMware Aria Suite Lifecycle vpostgres must have log collection enabled
  tags: [VLMP-8X-000070]
  block:
    - name: VLMP-8X-00070 - Verify log collector configuration is enabled or not
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW logging_collector;"
      register: log_coll_out
      changed_when: false

    - name: VLMP-8X-000070 - Update log collector to on
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET logging_collector TO 'on';"
      when: log_coll_out.stdout != "on"
      register: set_log_coll
      changed_when: set_log_coll.rc == 0
      notify:
        - Restart Postgres

##################################################################################################################################

# VLMP-8X-000075 - VMware Aria Suite Lifecycle vpostgres must use UTC for log timestamps.
- name: VLMP-8X-000075 - VMware Aria Suite Lifecycle vpostgres must use UTC for log timestamps
  tags: [VLMP-8X-000075]
  block:
    - name: VLMP-8X-00075 - Verify log timezone configuration
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_timezone;"
      register: log_tz_out
      changed_when: false

    - name: VLMP-8X-000075 - Update log timezone configuration to UTC
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET log_timezone TO 'Etc/UTC';"
      when: log_tz_out.stdout != "Etc/UTC"
      register: set_log_tz
      changed_when: set_log_tz.rc == 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000110 - VMware Aria Suite Lifecycle vpostgres must log all connection attempts.
- name: VLMP-8X-000110 - VMware Aria Suite Lifecycle vpostgres must log all connection attempts
  tags: [VLMP-8X-000110]
  block:
    - name: VLMP-8X-000110 - Verify log connection configuration is on or not
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_connections;"
      register: log_conn_out
      changed_when: false

    - name: VLMP-8X-000110 - Update log connection to on
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET log_connections TO 'on';"
      when: log_conn_out.stdout != "on"
      register: set_log_conn
      changed_when: set_log_conn.rc == 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000114 - VMware Aria Suite Lifecycle vpostgres must log all client disconnections.
- name: VLMP-8X-000114 - VMware Aria Suite Lifecycle vpostgres must log all client disconnections.
  tags: [VLMP-8X-000114]
  block:
    - name: VLMP-8X-000114 - Verify log collection configuration for disconnections is on or not
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_disconnections;"
      register: log_dconn_out
      changed_when: false

    - name: VLMP-8X-000114 - Update log collection for disconnections to on
      ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "ALTER SYSTEM SET log_disconnections TO 'on';"
      when: log_dconn_out.stdout != "on"
      register: set_log_dconn
      changed_when: set_log_dconn.rc == 0
      notify:
        - Restart Postgres

###################################################################################################################################

# VLMP-8X-000122 - VMware Aria Suite Lifecycle vpostgres must off-load audit data to a separate log management facility.
# This is a manual fix.
## Setup log_destination, syslog_facility & syslog_ident specific to the environment.
