---

- name: restart syslog
  ansible.builtin.service:
    name: syslog
    state: restarted

- name: restart perfcharts
  ansible.builtin.command: vmon-cli --restart perfcharts
  register: output
  changed_when: output.rc == 0
