# Backup files that may be modified in case restoration is needed
- name: Backup nginx configuration file
  tags: always
  block:
    - name: Backup nginx.conf - Create time stamp
      ansible.builtin.set_fact:
        backup_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

    - name: Backup nginx.conf - If restoring be sure to restore permissions that original file had!!
      ansible.builtin.copy:
        remote_src: true
        src: "{{ nginx_conf_file }}"
        dest: "/tmp/ansible-backups-vrlcm-nginx-{{ backup_timestamp }}/"
        mode: preserve
      changed_when: false

###################################################################################################################################

# VLMN-8X-000007 - The VMware Aria Suite Lifecycle web service must generate log records for system events.
- name: VLMN-8X-000007 - The VMware Aria Suite Lifecycle web service must generate log records for system events
  tags: [VLMN-8X-000007]
  block:
    - name: VLMN-8X-000007 - Verify error_log directive
      ansible.builtin.shell: nginx -T 2>&1 | grep "^error_log"
      register: err_log
      changed_when: false
      ignore_errors: true

    - name: VLMN-8X-000007 - Add error_log directive in main context
      ansible.builtin.lineinfile:
        path: "{{ nginx_conf_file }}"
        regexp: "^error_log *"
        line: "error_log {{ nginx_log_dir }}/error.log info;"
        insertbefore: "http *{"
        state: present
      when: err_log.stdout == "" or "info" not in err_log.stdout
      notify:
        - Reload NGINX

###################################################################################################################################

# VLMN-8X-000019 - The VMware Aria Suite Lifecycle web service log files must only be accessible by privileged users.
- name: VLMN-8X-000019 - The VMware Aria Suite Lifecycle web service log files must only be accessible by privileged users
  tags: [VLMN-8X-000019]
  block:
    - name: VLMN-8X-000019 - Check log file permissions
      ansible.builtin.shell: find {{ nginx_log_dir }}/* -xdev -type f -a '(' -perm -640 -o -not -user root -o -not -group root ')' -exec ls {} \;
      register: list_files
      changed_when: false

    - name: VLMN-8X-000019 - Verify and update file permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: file
        owner: 'root'
        group: 'root'
        mode: '640'
      with_items: "{{ list_files.stdout_lines }}"

###################################################################################################################################
# VLMN-8X-000025: The VMware Aria Suite Lifecycle web service must not perform user management for hosted applications.
# This is a manual fix.

###################################################################################################################################
# VLMN-8X-000026: The VMware Aria Suite Lifecycle web service must only contain modules necessary for operation.
# This is a manual fix.

###################################################################################################################################
# VLMN-8X-000034: The VMware Aria Suite Lifecycle web service must have Web Distributed Authoring (WebDAV) disabled.
# This is a manual fix.

###################################################################################################################################

# VLMN-8X-000036 - The VMware Aria Suite Lifecycle web service must not have any symbolic links that traverse outside the web content directory tree.
- name: VLMN-8X-000036 - The VMware Aria Suite Lifecycle web service must not have any symbolic links that traverse outside the web content directory tree
  tags: [VLMN-8X-000036]
  block:
    - name: VLMN-8X-000036 - Search for root directories and list symlinks
      ansible.builtin.shell: |
        set -o pipefail
        nginx -T 2>&1 | grep "root /" | awk -F" " '{print $2}' | awk -F";" '{system("find " $1 " -type l")}'
      register: root_dirs
      changed_when: false

    - name: VLMN-8X-000036 - Remove symlinks if any
      ansible.builtin.command: unlink {{ item }}
      with_items:
        - "{{ root_dirs.stdout_lines | unique }}"
      changed_when: root_dirs.stdout_lines | length > 0

###################################################################################################################################

# VLMN-8X-000040 - The VMware Aria Suite Lifecycle web service private keys must be protected from unauthorized access.
- name: VLMN-8X-000040 - The VMware Aria Suite Lifecycle web service private keys must be protected from unauthorized access
  tags: [VLMN-8X-000040]
  block:
    - name: VLMN-8X-000040 - Search for ssl cert keys
      ansible.builtin.shell: |
        set -o pipefail
        nginx -T 2>&1 | grep ssl_certificate_key | awk -F" " '{print $2}' | awk -F";" '{print $1}'
      register: ssl_certs
      changed_when: false

    - name: VLMN-8X-000040 - Set appropriate permissions for the cert keys
      ansible.builtin.file:
        path: "{{ item | trim }}"
        state: file
        owner: 'root'
        group: 'root'
        mode: '400'
      with_items: "{{ ssl_certs.stdout_lines }}"

###################################################################################################################################
# VLMN-8X-000041: The VMware Aria Suite Lifecycle web service must use FIPS 140-2 validated cryptographic modules.
# This is a manual fix.

###################################################################################################################################

# VLMN-8X-000062 - The VMware Aria Suite Lifecycle web service must disable directory listings.
- name: VLMN-8X-000062 - The VMware Aria Suite Lifecycle web service must disable directory listings
  tags: [VLMN-8X-000062]
  block:
    - name: VLMN-8X-000062 - Verify autoindex
      ansible.builtin.shell: nginx -T 2>&1 | grep "autoindex"
      register: auto_ind
      changed_when: false
      ignore_errors: true

    - name: VLMN-8X-000062 - Remove autoindex directive
      ansible.builtin.lineinfile:
        path: "{{ nginx_conf_file }}"
        line: "{{ item }}"
        state: absent
      when: auto_ind.stdout != ""
      with_items: "{{ auto_ind.stdout_lines }}"
      notify:
        - Reload NGINX

###################################################################################################################################

# VLMN-8X-000063 - The VMware Aria Suite Lifecycle web service must minimize the identity of the web server in information displayed to clients.
- name: VLMN-8X-000063 - The VMware Aria Suite Lifecycle web service must minimize the identity of the web server in information displayed to clients
  tags: [VLMN-8X-000063]
  block:
    - name: VLMN-8X-000063 - Verify server_tokens
      ansible.builtin.shell: nginx -T 2>&1 | grep "server_tokens"
      register: server_token
      changed_when: false
      ignore_errors: true

    - name: VLMN-8X-000063 - Remove server_tokens directive
      ansible.builtin.lineinfile:
        path: "{{ nginx_conf_file }}"
        line: "{{ item | trim }}"
        state: absent
      when: item != ""
      with_items: "{{ server_token.stdout_lines }}"
      notify:
        - Reload NGINX

    - name: VLMN-8X-000063 - Add server_tokens directive in http block
      ansible.builtin.lineinfile:
        path: "{{ nginx_conf_file }}"
        line: "  server_tokens off;"
        insertafter: "http *{"
        state: present
      notify:
        - Reload NGINX

###################################################################################################################################

# VLMN-8X-000078 - The VMware Aria Suite Lifecycle web service configuration files must only be accessible to privileged users.
- name: VLMN-8X-000078 - The VMware Aria Suite Lifecycle web service configuration files must only be accessible to privileged users
  tags: [VLMN-8X-000078]
  block:
    - name: VLMN-8X-000078 - Search for conf files
      ansible.builtin.shell: find /etc/nginx -xdev -type f -a '(' -perm -o+w -o -not -user root -o -not -group root ')' -exec ls {} \;
      register: list_files
      changed_when: false

    - name: VLMN-8X-000078 - Set appropriate permissions for the conf files
      ansible.builtin.file:
        path: "{{ item | trim }}"
        state: file
        owner: 'root'
        group: 'root'
        mode: '644'
      with_items: "{{ list_files.stdout_lines }}"

###################################################################################################################################

# VLMN-8X-000096 - The VMware Aria Suite Lifecycle web service must remove the default web site configuration.
# This is a manual fix

###################################################################################################################################
# VLMN-8X-000097: The VMware Aria Suite Lifecycle web service must remove references of server information from default web pages.
# This is a manual fix.

###################################################################################################################################

# VLMN-8X-000102 - The VMware Aria Suite Lifecycle web service must disable SSL session tickets.
- name: VLMN-8X-000102 - The VMware Aria Suite Lifecycle web service must disable SSL session tickets
  tags: [VLMN-8X-000102]
  block:
    - name: VLMN-8X-000102 - Verify ssl_session_tickets
      ansible.builtin.shell: nginx -T 2>&1 | grep "ssl_session_tickets"
      register: ssl_ssn_tckt
      changed_when: false
      ignore_errors: true

    - name: VLMN-8X-000102 - Remove ssl_session_tickets directive
      ansible.builtin.lineinfile:
        path: "{{ nginx_conf_file }}"
        line: "{{ item }}"
        state: absent
      when: item != ""
      with_items: "{{ ssl_ssn_tckt.stdout_lines }}"
      notify:
        - Reload NGINX

    - name: VLMN-8X-000102 - Add ssl_session_tickets directive in http block
      ansible.builtin.lineinfile:
        path: "{{ nginx_conf_file }}"
        line: "  ssl_session_tickets off;"
        insertafter: "http *{"
        state: present
      when: item != ""
      with_items: "{{ ssl_ssn_tckt.stdout_lines }}"
      notify:
        - Reload NGINX
