---

- name: restart syslog
  ansible.builtin.service:
    name: syslog
    state: restarted

- name: restart vsphere-ui
  ansible.builtin.command: vmon-cli --restart vsphere-ui
  register: output
  changed_when: output.rc == 0
