---
# handlers file for photon3

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: reload auditdconf
  ansible.builtin.command: pkill -SIGHUP auditd
  notify: start auditd
  register: output
  changed_when: output.rc == 0

- name: start auditd
  ansible.builtin.systemd:
    name: auditd
    state: started

- name: reload auditdrules
  ansible.builtin.command: /sbin/augenrules --load
  register: output
  changed_when: output.rc == 0

- name: restart syslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: restart ntp
  ansible.builtin.systemd:
    name: ntpd
    state: restarted

- name: restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
