---

- name: restart syslog
  ansible.builtin.service:
    name: syslog
    state: restarted

- name: restart lookupsvc
  ansible.builtin.command: vmon-cli --restart lookupsvc
  register: output
  changed_when: output.rc == 0
